{ config, pkgs, ... }:
{
  programs = {
    home-manager.enable = true;
    git = {
      enable = true;
      userName = "Bahar KURT";
      userEmail = "kurtbahartr@users.noreply.github.com";
      lfs.enable = true;
    };
    gh.enable = true;
    ssh.enable = true;
    hyfetch = {
      enable = true;
      # Ported from my preferences generated by going through the setup.
      settings = {
        preset = "genderfae";
        mode = "rgb";
        light_dark = "dark";
        lightness = 0.65;
        color_align = {
          mode = "horizontal";
        };
        backend = "fastfetch";
      };
    };
  };
  home = {
    username = "nix-on-droid";
    homeDirectory = "/data/data/com.termux.nix/files/home";
    file = {
      ".gitconfig".text = ''
        [core]
        editor=hx

        [color]
        ui=auto
      '';
    };
    packages = with pkgs; [
      fastfetch
    ];
    stateVersion = "24.05";
  };
}
